version: 2.1
orbs:
  node: circleci/node@4.1
jobs:
  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Deploy
          command: | 
            ssh ubuntu@${EC2_IP} 'cd ~/charlesqportfolio/portfolio && git pull && yarn && yarn build && pm2 restart all' 
workflows:
  version: 2
  deploy:
    jobs:
      - deploy