version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.1
  node: circleci/node@5.1

jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - node/install:
          node-version: latest
          install-yarn: true
      - run: cd portfolio && yarn 
      - run: cd portfolio && yarn build
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: portfolio/out
          to: 's3://youlinqu.com'
          overwrite: true

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main