version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Deploy
          command: | 
            ssh ubuntu@${EC2_IP} 'cd ~/charlesqportfolio/portfolio && git pull && yarn && yarn build && pm2 restart all' 
workflows:
  version: 2
  deploy:
    jobs:
      - deploy