version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.1
  aws-cli: circleci/aws-cli@3.1
  node: circleci/node@4.1

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - out
  deploy:
    executor:
      name: aws-cli/default
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-cli/setup
      - aws-s3/sync:
          arguments: --acl public-read --cache-control 'max-age=86400'
          from: /tmp/workspace/out
          to: 's3://youlinqu.com'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
