version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5
  node: circleci/node@5.1

jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - node/install:
          node-version: latest
          install-yarn: true
      - run: cd portfolio && yarn 
      - run: cd portfolio && yarn build
      - persist_to_workspace:
          root: portfolio/out
          paths:
            - .
      - run: ls portfolio
      - aws-cli/setup
      - run:
          name: Deploy to S3
          command: |
            aws s3 sync /portfolio/out s3://quyoulin.com --acl public-read --cache-control "max-age=86400"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main