version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Deploy
          command: | 
            ssh -o StrictHostKeyChecking=no ubuntu@${EC2_IP} \
            "
            cd ~/charlesqportfolio/portfolio && \
            pm2 stop next-app && \
            git pull && \ 
            yarn && \ 
            yarn build && \
            pm2 start next-app
            "
workflows:
  version: 2
  deploy:
    jobs:
      - deploy