AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    web-apis

Parameters:
    GoogleServiceParamName:
        Type: String
        Default: /personal-web/google-service-key
        Description: Google Service Account Key Name
    ResumeDocId:
        Type: AWS::SSM::Parameter::Value<String>
        Default: /personal-web/resume-doc-id
        Description: Google Doc Id for Resume

Globals:
    Function:
        Timeout: 10
        LoggingConfig:
            LogFormat: JSON
Resources:
    HelloWorldFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: src/
            Handler: hello-world.lambdaHandler
            Runtime: nodejs20.x
            Architectures:
                - x86_64
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /hello
                        Method: get
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                Sourcemap: true
                EntryPoints:
                    - hello-world.ts
    FetchResumeFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: fetch-resume.lambdaHandler
            Runtime: nodejs20.x
            MemorySize: 256
            Architectures:
                - x86_64
            Events:
                FetchResume:
                    Type: Api
                    Properties:
                        Path: /resume
                        Method: get
            Policies:
                - SSMParameterReadPolicy:
                    ParameterName: "*"
            Environment:
                Variables:
                    GOOGLE_SERVICE_PARAM_NAME: !Ref GoogleServiceParamName
                    RESUME_DOC_ID: !Ref ResumeDocId
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                Sourcemap: true
                EntryPoints:
                    - fetch-resume.ts
    ApplicationResourceGroup:
        Type: AWS::ResourceGroups::Group
        Properties:
            Name:
                Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
            ResourceQuery:
                Type: CLOUDFORMATION_STACK_1_0
    ApplicationInsightsMonitoring:
        Type: AWS::ApplicationInsights::Application
        Properties:
            ResourceGroupName:
                Ref: ApplicationResourceGroup
            AutoConfigurationEnabled: "true"
Outputs:
    HelloWorldApi:
        Description: API Gateway endpoint URL for Hello World function
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/api/hello/"
    FetchResumeApi:
        Description: API Gateway endpoint URL for Fetch Resume function
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/api/resume/"